plugin: aws_ec2
regions:
  - ap-northeast-2
filters:
  instance-state-name: running
hostnames:
  - private-ip-address
keyed_groups:
  - key: tags.Name
    prefix: name  
  - key: tags.aws:autoscaling:groupName
    prefix: group  
compose:
  ansible_host: private_ip_address  
  private_ip: private_ip_address