---
- name: Configure tomcat-PUB-2A instance
  hosts: name_VEC_PRD_VPC_TOMCAT_PRI_2A:name_VEC_PRD_VPC_TOMCAT_PRI_2C
  become: yes
  vars:
    html_files:
      - create-survey.html
      - start-survey.html
      - take-survey.html
      - view-survey.html
      - list-survey.html
    src_path: /home/ec2-user/html
    dest_path: /var/lib/tomcat/webapps/ROOT
    user_name: tomcat-webserver

  tasks:
    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Tomcat
      yum:
        name:
          - tomcat
          - tomcat-webapps
          - tomcat-admin-webapps
        state: present

    - name: Start and enable Tomcat
      systemd:
        name: tomcat
        state: started
        enabled: yes

    - name: Upgrade and install required packages
      yum:
        name:
          - curl
          - wget
          - unzip
          - nano
          - vim
          - net-tools
          - python-firewall
        state: present

    - name: Create user {{ user_name }}
      user:
        name: "{{ user_name }}"
        state: present
        shell: /bin/bash

    - name: Create source HTML directory if it does not exist
      file:
        path: "{{ src_path }}"
        state: directory
        owner: ec2-user
        group: ec2-user

    - name: Create destination HTML directory if it does not exist
      file:
        path: "{{ dest_path }}"
        state: directory
        owner: tomcat
        group: tomcat

    - name: Copy HTML files to Tomcat directory
      copy:
        src: "{{ src_path }}/{{ item }}"
        dest: "{{ dest_path }}/{{ item }}"
        owner: tomcat
        group: tomcat
        mode: '0644'
      with_items: "{{ html_files }}"
      ignore_errors: yes

    - name: Copy create-survey.html to index.html
      command: cp {{ dest_path }}/create-survey.html {{ dest_path }}/index.html
      ignore_errors: yes
